### ISSUE TITLE
[South - OPCUA] - Bad settings display

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#1020]
On OPCUA with medium screen, ScanGroups and OPCUA settings are not displayed correctly.

**To Reproduce**
Go to OPCUA South Connector, reduce a little bit the screen like in the screenshot, and see the bug.

**Expected behavior**
The scan groups and OPCUA settings should be displayed the same way than the Loggin parameters.

**Screenshots**
![image](https://user-images.githubusercontent.com/28055217/103670250-9edf3f00-4f79-11eb-8db9-ece24c7557f7.png)

**Comment by attilasuto** [comment]
@burgerni10 can you please give more details on the problem? The fields should be aligned and have the same width as the Logging parameters? 

![issue](https://user-images.githubusercontent.com/47381370/103898799-2655bb00-50fe-11eb-9a00-2b0724f3688d.png)

**Comment by burgerni10** [comment]
Yes I think it would be better, so the scan mode fields will be more readable this way.
