### ISSUE TITLE
[South - MQTT] - Offer the possibility to establish a persistent connection

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#1021]
Persistent connections are available in MQTT for QoS 1 & QoS2 : I think we should offer an option to support that as a MQTT client. Here is a quick summary of that : http://www.steves-internet-guide.com/mqtt-clean-sessions-example/

With the node mqtt package, this option is the parameter _clean_ in the connection options.

**Comment by kukukk** [comment]
Based on the documentation it is not enough to disable `clean session` and set QOS > 0 on the subscriber side. The publisher must also connect using QOS > 0. Should it be documented on the UI?
It also requires a persistent client ID on the subscriber side. Should it be configurable by the user or hard-code it to eg. `OIBus`? I think the value is not relevant, but has to be something unique, so the MQTT server can recognize the client. So, in case of multiple OIBus connection to the same MQTT server using the same client ID can cause problems.

**Comment by burgerni10** [comment]
The clean session should be offered only whith QoS1 or QoS2, and a warning (or regular documentation) should tell the user that the clean session will be used only if supported by the broker.

Maybe the client ID can also be reset or just set by the user from the MQTT connector so we can restart and identify the connection better (for debugging for example). If the client ID field is empty, so it can be generated automatically like 'OIBus-<random_number>' with random number large enough to assure a unique client ID.
This has to be documented for the user of course.

In this case, the client ID should be saved in the config file. What do you think about this ?

@jfhenon do you see other use cases / options for this mqtt client ID / session ?

**Comment by jfhenon** [comment]
No but only question is why save to the config file and not SQLite.

**Comment by burgerni10** [comment]
If the user can modify it for connection purposes, it is more a setting than a variable, so it should be stored in the config file I think.
On the other hand, if the client id is generated automatically, it is more a variable, and should be stored in SQLite. It depends how we choose to see the client ID...

**Comment by kukukk** [comment]
Right now we don't have such functionality to make available a field based on another field. If documenting the situation when the clean session will have effect is not enough, I will ask @attilasuto to help modifying the checkbox component to have an enabled/visible function which can use the value of an another field.

The default value for client ID is `clientId: 'mqttjs_' + Math.random().toString(16).substr(2, 8)`. If client ID is not specified I can use the same logic to generate it, but replace `mqttjs_` with `OIBus-`. It would look like: `OIBus-b403429b`

If client ID can be specified on the UI, I think it should be handled the same way as other parameters.
