### ISSUE TITLE
Make sure a south handler resets/restores the protocol connection when the source was stopped and restarted.

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#1039]
Decision to be made : Do we make this generic for all protocols (or use native capabilities for some protocols)?

**Comment by burgerni10** [comment]
MQTT has a keepalive function that can be set with the connection parameters. This way, we can detect a restart or a disconnection and start the connection again with the connection timeout.

OPCUA has something similar but I need to check that.

Modbus is trickier and a reconnection routine must be implemented when a 'disconnect' event occurs.

I think each protocol has its own way of doing and it should be separated issues. I would tend to focus on MQTT and then OPCUA, and maybe later on OPC-HDA and Modbus

**Comment by burgerni10** [comment]
Done with MQTT and Modbus

Need to check the reconnection on OPCUA / OPC-HDA
