### ISSUE TITLE
UnhandledPromiseRejectionWarning in WATSYConnect.class.spec.js

### ISSUE THREAD

**Issue by kukukk** [OptimistikSAS/OIBus#1049]
**Describe the bug**
When running test it throws an unhandled promise rejection: `UnhandledPromiseRejectionWarning: TypeError: callback is not a function`

**To Reproduce**
npx jest src/north/watsyconnect/WATSYConnect.class.spec.js

**Expected behavior**
Tests running without UnhandledPromiseRejectionWarning

**Screenshots**
![Screenshot from 2021-01-19 16-43-11](https://user-images.githubusercontent.com/616786/105049623-85f48480-5a75-11eb-91f4-2569ae37d204.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
`WATSYNorth.client.publish` is not properly mocked. It is called with 4 parameters, but mocked with only 1.

**Comment by jfhenon** [comment]
with the PR #1048
