### ISSUE TITLE
Manage MQTT connection failure, keep alive and connection timeout

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#1050]
When the MQTT broker restart, the OIBus south connector MQTT must reconnect on its own and detect the connection failure.

To do that, see the following mqtt connection options : 
keepalive
reconnectPeriod
connectTimeout

These parameters must be set in the config.json (and manage from the mqtt interface) with default values (to be determined)

**Comment by kukukk** [comment]
Any update on the default values?

Should we show information about the connection status on the UI?
