### ISSUE TITLE
Bearer token authentication (OIbAuthentication & Request)

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#1056]
Manage bearer token authentication in OIbAuthencation component and in the backend request authentication

**Comment by kukukk** [comment]
Actually, Bearer token authentication is like the "API Key" authentication where "key" is "Bearer" and "secretKey" is the token?

**Comment by burgerni10** [comment]
Thank you for your PR !

The token should indeed be encrypted, as you have done.

Bearer authentication fills the header field Authorization with 'Bearer <token>' whereas API key fills the header field <key> with the value <secretKey>. 

From your PR, I guess you understood that. I write it here for general info.
