### ISSUE TITLE
[North-CsvToHttp] Use variable in input's field

### ISSUE THREAD

**Issue by victor-tndl** [OptimistikSAS/OIBus#1076]
This feature aim to let the use the choice to use variable in input's field. He'll be able to concatenate string using template string. This feature is related to #1005.

For example:
A North "CsvToHttp" receives a CSV file from a South. Inside, we have 2 headers called "header1" (its value is "example1" for each row) and "header2" (its value is "example2" for each row)
The user wants a custom output which is the concatenation of both headers.  The user will set the field "Header in csv file" to  "${header1} and ${header1}".

In this case, the result will be "example1 and example2".

In order to implement this, the code may be something like this:
```js
public function convert(value){
     result = eval('`'+value+'`')
     return result
}
```

Let me know if everything is ok for you (@burgerni10 @jfhenon ).

**Comment by jfhenon** [comment]
I would not approve a PR using eval() which causes security concerns. If you need to concatenate strings, you have several packages that could be used instead. 
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/eval

**Comment by victor-tndl** [comment]
I was pretty sur that it would not have been approuved. I'll try to find another way to use variable.

However, is aim fo this feature ok four you?

**Comment by burgerni10** [comment]
I agree with JF, eval should be avoided.

I think the feature can be useful. You can start thinking more about it (without eval of course !).

We must discuss internally a little bit more about the way the variables are defined : in SqlDbToFile, we use @variable but something code-like as you propose may be better. @jfhenon what do you think ?

**Comment by jfhenon** [comment]
our MQTT handler (and others) uses sprintf-js. This should be good for the use case above.
JF

**Comment by victor-tndl** [comment]
I already used regex in my solution
