### ISSUE TITLE
error message on OIBus start

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#1119]
```
(node:13648) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```
This message does not cause an issue with OIBus (I didn't test the Mongo North Handler) but we need to understand the issue and remove it.

**Comment by burgerni10** [comment]
I've seen it when I updated the mongodb package. Apparently the warning is safe and it will be fix soon : https://developer.mongodb.com/community/forums/t/warning-accessing-non-existent-property-mongoerror-of-module-exports-inside-circular-dependency/15411/6
