### ISSUE TITLE
Improve table styling

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#1139]
![image](https://user-images.githubusercontent.com/20402845/110250038-973c1680-7f79-11eb-9cfe-0e48fd25ac21.png)

based on the work of @Lulu300 on Modbus, I think we need to improve the table component. 

1/ The help text should be below the column headers to avoid repeating it on each rows.
It can also be a help section with a (?) sign somewhere:
![image](https://user-images.githubusercontent.com/20402845/110250210-70321480-7f7a-11eb-969c-869e493588c5.png)

2/ The column width should be a parameter for each column. I propose to add an optional parameter **width** to the schema.points object that will be applied to the <th> of the table 
`````
schema.points = {
  pointId: {
    type: 'OIbText',
    valid: notEmpty(),
    defaultValue: '',
    width: '10%',
  },
 /* .... */ 
}

export default schema
````

**Comment by burgerni10** [comment]
I prefer that the help menu : it will be easier to display examples and explanations for each header

**Comment by attilasuto** [comment]
I've started working on this task 
and point 1 is done. Please check the attached screenshot, I've added a table help OIbTitle expandable section with the value for help on each point column. The help can be a simple text or html depending on the need. Please confirm if this is the expected UI.
Work started on PR: #1221
<img width="1180" alt="table_help" src="https://user-images.githubusercontent.com/47381370/117432279-db747480-af32-11eb-803a-4e6a90cd5f5d.png">

**Comment by burgerni10** [comment]
Perfect, thank you ! 
Let us know when it's ready for code review.

**Comment by attilasuto** [comment]
Help section(1.) and column width(2.) is ready for code review.
