### ISSUE TITLE
MQTT - fail to listen to a point when it's listed twice

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#1140]
When a point is listed twice in the MQTT point list, we receive no value at all.

The first subscription should be done, and the second one is ignored, which triggers a warning in the logger.

**Comment by burgerni10** [comment]
We need to manage when the connector subscribes to a point with a wildcard AND a specific subscription

**Comment by kukukk** [comment]
How should it be handled? Possible options I see:
  - check on the UI if there are overlapping points and disable saving until the user fixes it
  - simply ignore the second point and skip the subscription
  - identify and subscribe only to the higher impact point

Simply ignoring the second one could cause data loss. E.g.: '/sensors/temperature1' vs '/sensors/*'. The second one could include tens of sensor values, but we will ignore it and only receive data from a single sensor.

**Comment by burgerni10** [comment]
Your first point must indeed be done. This logic may be used again in other connector (like OPC) in a later issue.

I think the third point solve the issue without data loss, so you can implement that and forget about the second point.

**Comment by burgerni10** [comment]
The backend part will be done with the issue #1104 

@attilasuto can you implement the frontend please ?

**Comment by attilasuto** [comment]
Please check merge request: #1247

The points config page will show error for any duplicated entry that has the 'unique = true' defined in the schema. Currently I've added the unique flag to pointId on MQTT.schema. This can be easily enabled on any protocol that requires a unique flag.
Please let me know if any change is required.
