### ISSUE TITLE
[South] - SQLite connector

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#1160]
A South connector must be implemented to get data from a SQLite database. It is used as a driver from SQLDbToFile connector. 

The settings of this connector should dynamically change. SQLite driver only has the path of the SQLite database, but other drivers do not have databasePath and have host, port, username...

**Comment by jfhenon** [comment]
Do you plan to reuse sqldbfile?

**Comment by burgerni10** [comment]
Yes : we have a use case where a Beckhoff PLC store events and alarms in a local SQLite data base that we need to request to send to a North.

**Comment by burgerni10** [comment]
@attilasuto I added the sqlite driver and appropriate settings for SQLite on the SQLDbToFile connector. Can you look at the front end to dynamically change the displayed settings depending on the driver ?
