### ISSUE TITLE
should we call this.send or this.httpSend??? where is defined this.send?

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#1164]
https://github.com/OptimistikSAS/OIBus/blob/d074c6955e7ef0832ebf42060b383771f0e1022b/src/services/request/BaseRequest.class.js#L107

**Comment by jfhenon** [comment]
I also think we need to add some debug/warning logs as this is difficult to understand what's going on when retries are done.

**Comment by kukukk** [comment]
It seems to me that RequestService refactoring was merged into master half-way done: https://github.com/OptimistikSAS/OIBus/blob/refactor-request-service%23981/src/services/request/BaseRequest.class.js#L107
