### ISSUE TITLE
Make sure SQL South can't modify the tables

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#1171]
I would like to know if SQLDbTofile South driver can write or delete to the table. If yes, I think we should not allow this (maybe by analysing SQL statements and make sure they don't contain WRITE, INSERT, DELETE etc...

**Comment by kukukk** [comment]
Should it be done on the backend by ignoring the query and logging an error?
Or do you prefer a validation to be done also on the Frontend?

**Comment by burgerni10** [comment]
I don't think this should be handle on OIBus, but rather in the Database itself by managing rights.

I know that for SQLite it may be tricky, but since these databases are locally stored, it is the responsibility of the user to not do something stupid with OIBus SQLite databases for example.

**Comment by jfhenon** [comment]
Nicolas, I agree that the ideal case would be to have a specific user for OIBus with read rights only but setup of access rights is very variable. I think it would be better to do a small validation on the backend.

**Comment by burgerni10** [comment]
So, should we forbid such requests or just show a big warning sign ?

**Comment by jfhenon** [comment]
I think it should ignore the query and logs an error on OIBus.

**Comment by kukukk** [comment]
How careful should we be? I mean, the user can specify a query like: `SELECT timestamp, value FROM table; DELETE * FROM table;`
Should we try to detect any `DELETE`, `UPDATE`, `DROP` appearances?

**Comment by marouanehassanioptimistik** [comment]
We need to be careful with this semantically analyzing a query may prove hard, update insert can be substring of column we might want to query so a naïve approach might not work. And if we want to be compréhensive than detecting any modifying query is very hard by just analyzing the query (and might be dB dependant). The best way to solve this is je rigorous and never use user with write access

**Comment by kukukk** [comment]
We could do a check if the query contains `DELETE`, `UPDATE` or `DROP` as a standalone world. So if they are substring of column we won't ignore the query.

**Comment by jfhenon** [comment]
This article is talking about that: 
https://stackoverflow.com/questions/8787044/check-for-read-only-query-string
Actually, they mention `SET TRANSACTION READ ONLY` , it would be interesting if this is supported by our databases.

**Comment by kukukk** [comment]
Who configures the SQL South knows all the credentials to connect to the database. If the used credential allows deleting/altering, the user can directly connect to the database and delete/alter data/schema, if there is an intention to do some damage. The only situation we should try to handle is a wrong copy+paste for the query, I think. For this a simple check for `DELETE`, `ALTER`, `DROP`, `UPDATE` could be enough. No need for comprehensive check.

Using `SET TRANSACTION READ ONLY` would require more work, because we have to check the proper way to use it for every database type we support.

**Comment by jfhenon** [comment]
For the short solution, we can document in the online help that OIBus user should be given readonly access to the DB.
