### ISSUE TITLE
[U/X] Help text

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#1217]
A suggestion: 
It appears that most people starting with OIBus are missing the fact they can click on the ? to get more information about the different fields. 
What about making the default behavior to have the text visible? 
It takes some space but it's not so important with a web interface that allow to scroll very conveniently.

**Comment by burgerni10** [comment]
Another suggestion : making the "help" icon lightly blink to suggest an interactive icon.

**Comment by burgerni10** [comment]
@attilasuto Do you have any UI suggestions for this issue ?
