### ISSUE TITLE
File not moved from cache to archived directory

### ISSUE THREAD

**Issue by matthieurolland** [OptimistikSAS/OIBus#1293]
Using a folderscanner connector, we get the following error and the user wrote :
" je remarque que des fichiers restent dans le dossier « cache » et ne basculent pas dans le dossier « archived » après avoir été importés"

/8/2021-3:06:00 AM
error
uncaughtException: EBUSY: resource busy or locked, open ‘\\--.--.local\data\APPLI\DATAEXTRACT\20210708-030000_historian_.csv’ Error: EBUSY: resource busy or locked, open ‘\\--.--.local\data\APPLI\DATAEXTRACT\20210708-030000_historian_.csv’

**Comment by burgerni10** [comment]
@kukukk I assigned this issue to you since you will refactor the cache in a near future. Basically, some files are not removed from the cache, probably because of concurrent access to the file
