### ISSUE TITLE
[UI] several UI issues

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#1322]
![image](https://user-images.githubusercontent.com/20402845/126357017-8368dd31-0a89-4440-a6f3-e181d163ffcb.png)
The pencil is too large
![image](https://user-images.githubusercontent.com/20402845/126357945-c33e33b5-5b0f-465e-97c9-cf35d981c9f3.png)
The check is also too large

![image](https://user-images.githubusercontent.com/20402845/126357607-5a597963-08d1-4e46-bc09-5af6b33d7075.png)
The refresh icon is too large

![image](https://user-images.githubusercontent.com/20402845/126357285-3f0d3170-1815-4a08-80ea-81a2ae357fe8.png)
The space between the up and the down arrows is too large

![image](https://user-images.githubusercontent.com/20402845/126358164-398aeaa3-c21b-4bea-b3e0-bc0e52fe3d2a.png)
The text for checkbox is too long. Maybe we should move the long label to help.

**Comment by burgerni10** [comment]
@franckfotso1 can you reduce the icon size (but not as small as it was before) ?
The last screenshot of JF is from Modbus, can you suggest and implement some improvements on it ?
