### ISSUE TITLE
[SQL] improve management of value recovery when sql source goes offline

### ISSUE THREAD

**Issue by marouanehassanioptimistik** [OptimistikSAS/OIBus#1327]
**Is your feature request related to a problem? Please describe.**
When a south sql connector is disconnected from its source for an extended period of time the last completedAt doesn't evolve. When the source goes up again this can lead to a query with a very large period which can reach timeouts or even not give result at all.

**Describe the solution you'd like**
We should manage better this case by splitting the query by a parameter and also in this case ignore the scan mode and execute the next request as soon as the previous request returned.

**Comment by burgerni10** [comment]
This issue should be fixed with the reworking regarding historyQuery #1347 which uses a maxReturnValues flag
