### ISSUE TITLE
Migration of Archive

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#1358]
https://github.com/OptimistikSAS/OIBus/blob/b68c7c1c16d447590caa45de49faeb1b62e5c6d6/src/migration/migrationRules.js#L488

The line above made my migration to fail 
Are we sure about `archiveFolder: config.engine.caching.archive.archiveFolder,`
should it be :  `archiveFolder: config.engine.caching.archiveFolder,` ?

**Comment by burgerni10** [comment]
Indeed. I make a PR to fix that
