### ISSUE TITLE
[UI - Point list] - Remove the wrong point when the list is filtered

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#1380]
**Describe the bug**
On every point protocols, on the point list, when the list is filtered, the deletion remove the wrong point

**To Reproduce**
1. Create a point connector (mqtt, ads...)
2. Go the the point list and add some points
3. Filter your list by entering something in the filter and make it so it remove some points of the list
4. Remove a point (the removed point index of the list is used, hence the error)

**Comment by dezse97** [comment]
I would extend this issue with the "edit" functionality, as it has the same behavior too.
