### ISSUE TITLE
[UI] - Display problem when renaming a connector

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#1807]
When renaming a connector, the confirm tick is not properly aligned.

![image](https://user-images.githubusercontent.com/28055217/174585683-95fe48ee-dbc6-458d-8561-70b5d9af2839.png)

**Comment by Reloflex** [comment]
![image](https://user-images.githubusercontent.com/15195992/189915897-6b3ede82-c4fa-4a45-bf84-5eb6222deabd.png)
![image](https://user-images.githubusercontent.com/15195992/189915909-c3b0dc80-bdcf-4297-b20f-7dd7e3871fe2.png)
