### ISSUE TITLE
OPCUA SOUTH - when trying scan modes, OIBus can be stuck

### ISSUE THREAD

**Issue by brunomaury** [OptimistikSAS/OIBus#1813]
Steps : 
In an already existing SOUTH OPCUA with points.
Change an already use scan mode : 
<img width="671" alt="image" src="https://user-images.githubusercontent.com/56166954/175573677-7a64fd55-bf16-42c2-b427-d597be34f2a1.png">
Go to activation
Read the error message : 
`{"south.dataSources.2.points.1354.scanMode":"Invalid scan mode","south.dataSources.2.points.1353.scanMode":"Invalid scan mode","south.dataSources.2.points.1352.scanMode":"Invalid scan mode","south.dataSources.2.points.1351.scanMode":"Invalid scan mode","south.dataSources.2.points.1350.scanMode":"Invalid scan mode","south.dataSources.2.points.1349.scanMode":"Invalid scan mode","south.dataSources.2.points.1348.scanMode":"Invalid scan mode","south.dataSources.2.points.1347.scanMode":"Invalid scan mode","south.dataSources.2.points.1346.scanMode":"Invalid scan mode","south.dataSources.2.points.1345.scanMode":"Invalid scan mode"}`

It's quite normal but even if after editing the scan mode in the south, you change the scan mode for every points, the error is still present.

**Comment by kukukk** [comment]
It seems that I found an another issue, closely related to this. To reproduce:
1. Add a new OPCUA_HA south
2. On the settings screen add a new ScanGroup: every10seconds
3. Add a second ScanGroup and choose the same every10seconds
4. It will show the error for both that the Scan mode already selected
5. Change the second to a different scan mode, like every1Min
6. Go to the Activation screen. It will show the following error: `{"south.0.settings.scanGroups.0.scanMode":"Scan mode already selected"}`
