### ISSUE TITLE
[Connector] - Remove associated cache folder when removing a connector

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#2056]
The cache folder stays on disk when the connector is removed.

It should be removed from disk.

**Comment by burgerni10** [comment]
As discussed, the removal of connector cache folder must be done on config activation:

https://github.com/OptimistikSAS/OIBus/blob/fb8c0ed0a8391375056ff857cc46c7df4d55a00c/src/service/configuration.service.js#L99-L110

Just after the writeFile and before this.config is set with the modified config. 

@kukukk any feedback on that ?

**Comment by kukukk** [comment]
Is any client using the possibility to manually alter the config file? If yes, then we can still end up with orphan cache folders. Or in this case they should also be aware to manually delete the cache folders?

**Comment by burgerni10** [comment]
> Is any client using the possibility to manually alter the config file? If yes, then we can still end up with orphan cache folders. Or in this case they should also be aware to manually delete the cache folders?

Manual operation is the client responsibility (or our responsibility if we do it). It's ok to have orphan folders in this case.
