### ISSUE TITLE
[South - Modbus] - Manage single bit variables

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#2893]
Some variables are stored in a bit, inside a holding register, discrete input, etc

To manage these variables:
- [ ] Add a 'bit' option in dataType (manifest)
- [ ] Add a 'bit index' settings (manifest)
- [ ] Adapt the serialisation in the getValueFromBuffer method

**Comment by kukukk** [comment]
Should `bit index` be visible only when the `bit` dataType is selected?

**Comment by burgerni10** [comment]
Yes, so you can use a conditionalDisplay on the manifest

**Comment by kukukk** [comment]
So, the flow is: 
 - when `inputRegister` or `holdingRegister` is selected as `modbusType` we show the `dataType` fields
 - when `bit` is selected as `dataType` we show `bit index` as `OibNumber`
 - we use `readInputRegisters` or `readHoldingRegisters` (depending on the selected `modbusType`) to read 1 word from the Modbus device at the specified `address`
 - we use `bit index` to get the request bit from the word
 
Or is there a specific Modbus TCP read instruction to get a single bit I don't know about?

**Comment by burgerni10** [comment]
Not that I know. So the bit extraction must be done in the OIBus connector.
