### ISSUE TITLE
[OPCUA] Tag list pagination not functional

### ISSUE THREAD

**Issue by mathieucura** [OptimistikSAS/OIBus#3065]
**Describe the bug**
The tag list in OPCUA south configuration is note paginated

**To Reproduce**
1. Go to South
2. Click on one OPCUA south
3. Tag list without pagination so able to see only the first 20 tags.

**Expected behavior**
We should be able to navigate in the tag list through pagination (no pagination appearing so many tags are not visible)

**Screenshots**
![south_taglist](https://github.com/OptimistikSAS/OIBus/assets/16381627/a15571fa-6c47-485d-87fd-bfcf90d1f462)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Additional context**

**Comment by marouanehassanioptimistik** [comment]
this is likely fixed by https://github.com/OptimistikSAS/OIBus/commit/1ad8db1f482023156240afabd16da0942d5a3948
