### ISSUE TITLE
[Scan Mode] - Test cron validity

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#3167]
On the frontend (scan mode creation / edition):
- Add a validator to check the form 
- Add a small text area to display the three next occurrence of the cron

On the backend
- Add a cron validator in the backend api (with joi)
- On the Cron instantiation, check the cron validity AND if the next occurrence is in the past* (if so, discard the Cron)

*0 35 10 19 01 2024 is a valid cron but a one time occurrence in the past. It crashes OIBus when the Cron is created

**Comment by nagyszabi** [comment]
For displaying a more human readable form of the cron, we could use the [cronstrue](https://www.npmjs.com/package/cronstrue) package.
It has a pretty impressive [demo](https://bradymholt.github.io/cRonstrue/#cronstrue-demo) as well.

It's very well documented, and supported. It also supports multiple languages.

**Comment by burgerni10** [comment]
Yes, I agree, and it seems we could use it to check the cron validity on the frontend.
