### ISSUE TITLE
South connector with queries

### ISSUE THREAD

**Issue by brunomaury** [OptimistikSAS/OIBus#3169]
For example in SQL south connectors
If the SQL are a bit long, it's : 
- Not easy to have a overview
- Not very helping to read the query which is compressed
- Very easy to miss the SAVE button bellow all queries
![image](https://github.com/OptimistikSAS/OIBus/assets/56166954/184bc71b-3689-4568-ac82-1624ef32e533)

**Comment by burgerni10** [comment]
I suggest an ellipsis for the specific_settings fields. On mouse hover, a small tooltip can display the full value of the field

**Comment by burgerni10** [comment]
I close this issue since the save button logic will be reworked with #3168
