### ISSUE TITLE
[UI] add a "Watch" menu

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#393]
- A watch screen that would be configured with a list of points. 
- Each time the point would be added to the cache, the watch screen would display the payload (timestamp, value, ..) 
- useful to follow the behavior of OIBus

**Comment by burgerni10** [comment]
We now have a cache page to explore its content and a live metrics update on the connector. I close this issue now, but we can create a new one later if we have more suggestions to interact with the data streams
