### ISSUE TITLE
add multi user capabilities

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#418]
right now, user/password is a single field, we could move this to a table if users to allow named users. While we do this, I think we should add a role as well for each users (only "admin" at this point).

**Comment by burgerni10** [comment]
We now have a user list with hashed password mechanism. It leads us toward multi-user capabilities but we do not have any need for it now. I close this issue for now, but we can create a new one if we need user changes tracking or permissions later.
