### ISSUE TITLE
implement compression when sending values to north applications

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#569]
We have a use case where the network is not so good and where compressing the values (which may compress very well) can be a solution. This should be an engine option because it may also impact performance significantly if the network is fast. 

Nodejs propose native compression: https://nodejs.org/dist/latest-v12.x/docs/api/zlib.html#zlib_compressing_http_requests_and_responses

**Comment by burgerni10** [comment]
On OIAnalytics, for retro-compatibility, we could use a route parameter `compressed` : if absent or false, it is the already existing endpoint that will be used ; if true, the new endpoint (to be develop) is used.

**Comment by kukukk** [comment]
Let's clarify some things...

Do you want an additional `compressed` option for OIConnect and OIAnalytics, also an option to specify `compressedValuesEndpoint`. When `compressed` is false we execute the same code as we do now. When it is `true` we compress the JSON content, set `Content-Encoding: gzip` and use a `compressedValuesEndpoint`?

Is the new endpoint developped?

**Comment by burgerni10** [comment]
The same endpoint will be used, only the parameters will change. 

For example, with no compression : /api/optimistik/oibus/data/time_values
With compression : /api/optimistik/oibus/data/time_values?compressed=true

But the @ParamMap on OIAnalytics Spring backend will route the parsing of the payload to a different function according to the compressed param. This is yet to be developed.

On OIConnect the same logic can be used.
For example, with no compression : /custom_endpoint
With compression : /custom_endpoint?compressed=true

**Comment by kukukk** [comment]
Ahh, ok. So we just need the `compressed` option to be added and properly handled. I will start working on it. Let me know when the OIAnalytics side is ready.

**Comment by burgerni10** [comment]
After some discussions with Marouane for the OIAnalytics part, we need to think more on the best way to implement it on the server side. 

In the meantime, I change the milestone of this one to "future" and I'll bring it back when we decide how to implement it on OIA.
