### ISSUE TITLE
Add a function to clear the cache

### ISSUE THREAD

**Issue by mathieucura** [OptimistikSAS/OIBus#575]
When cache is saturated with to many file, it could be great to have a function to clean it properly.

**Comment by burgerni10** [comment]
This feature is needed for HistoryQuery Cache

**Comment by burgerni10** [comment]
When many data are stored in a SQLite database, its size grows, but do not reduce when the entries are removed. I think this function should also pause OIBus, and reduce the size of the SQLite database file on disk.
