### ISSUE TITLE
Add a sorting functionality in the NORTH and SOUTH list

### ISSUE THREAD

**Issue by brunomaury** [OptimistikSAS/OIBus#713]
Hi,
It would be nice, in order to keep everything clean, to be able to sort the South/north list manually or by column (Data Source ID or Protocol).

**Comment by attilasuto** [comment]
I've started working on this task and just to be sure I understand correctly please confirm the following is required:
- North/South lists should be sortable by clicking on the Application ID/ Data Source Id column header in ascending and descending order by toggle this with each click
- Also each row should be movable separately row by row by swap places with the upper/below item.
- This will be just visually, will not have effect to the active configuration and will not be saved in the config. 

Please confirm or provide more details if something is not accurate.

**Comment by brunomaury** [comment]
The first point is indeed what I had in mind.

For the following points :
If it's not saved in the configuration, the user will have to sort again if he/she disconnect/reconnect ?
If this is correct, the manual sort isn't very useful so I think we must decide if this have an effect on the configuration or if the manual sort can be discarded.

**Comment by attilasuto** [comment]
Yes, if not saved will have to sort again. If we save the order that it will appear as "Modifications" in the active config and will need to Accept/Decline on the "Activation" page.
If we just need a quick sort in ascending/descending order I think we don't need to save this in the config.

**Comment by brunomaury** [comment]
I think we can go with the sort by ascending/descending order for now.
So without the manual sort and without effect on the configuration.

Is it possible to add a "Protocol" column in the list to display the NORTH/SOUTH protocol (SQL Driver, MQTT, etc.).
That would be a convenient column to sort.
