### ISSUE TITLE
suppress warning with pkg build because fsevents.node is missing

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#765]
**My tests seem to indicate that this warning does not cause a runtime issue.** 

 FSevents is only useful on MacOS to to register for notifications of changes to a given directory tree.
This module is used by node-opcua-pki (used by node-opcua to create a Public Key Infrastructure) and more specifically by one of its dependencies called Chokidar https://www.npmjs.com/package/chokidar.

pkg issue a warning because it can't find this .node but as we only supports Windows for production, we should not have an issue.

**Comment by burgerni10** [comment]
I think this issue disappeared with the latest changes. However, I now have other warnings to take care of :)
