### ISSUE TITLE
[North CSV] North Handler receiving values, transforming them into a CSV file and load the file to a specified directory

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#940]

**Comment by burgerni10** [comment]
Should it be an improvement of the File writer connector ?

**Comment by jfhenon** [comment]
Yes, it makes sense.

**Comment by burgerni10** [comment]
For now, FileWriter can write values as json files.

An option can be added to the connector to ask if we want to write values as json (default behaviour) or csv. There is something done in CsvToHttp that allows to write json from csv by selecting the fields. Maybe something similar can be done here

**Comment by burgerni10** [comment]
Issue linked with #854 and waiting for the rework of North connectors #2607 to add transform capabilities
