### ISSUE TITLE
North/South Handlers to support an icon

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#942]
This will be used in Home screen / Configuration screens, ...  
![image](https://user-images.githubusercontent.com/20402845/98953418-f5417b80-24fc-11eb-8a50-4cd41803a3b5.png)

**Comment by jfhenon** [comment]
Proposal to start this. You can start with icons.logos (they should be monochrome so we can keep the green/grey color for enabled/disabled.
Any handler will have the ability to have a file (logo.svg) in its folder to be displayed in the configuration screen as well as on the homepage table. If the logo.svg file is not present, the file will use a default icon.
The logo should not be too large.

**Comment by burgerni10** [comment]
I wonder if having monochrome logos is the right move : is it not better to have a grayscale logo when disabled, and the default coloured logo if enabled ?
In this case, we may rethink the "console" logo a little bit to make it clearer it is enabled or disabled.
