### ISSUE TITLE
Interesting library if we want to have a more graphical view of OIBus

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#961]
https://github.com/projectstorm/react-diagrams

**Comment by burgerni10** [comment]
What do you have in mind with this enhancement ?

**Comment by jfhenon** [comment]
The way to represent North/Engine/South connections (currently represented with a table today in the home page of OIBus)

**Comment by burgerni10** [comment]
Can I close this issue now that the new UI is astonishingly nice ?
