### ISSUE TITLE
Refactor the Cache

### ISSUE THREAD

**Issue by kukukk** [OptimistikSAS/OIBus#974]
The actual Cache implementation is quite complex and hard to maintain. I think we should separate at least handling files and values into separate ValueCache and FileCache implementations.

Maybe we could create and attach a separate Cache instance to every North (or 2 if the North supports both values and files). This way the Cache implementation would be even simpler

**Comment by jfhenon** [comment]
Additional thoughts: 
- use of nodejs eventEmitter to communicate between the cache and north/south handlers 
- should we remove sqlite (to avoid the .node) with another native db (I have seen some)
