### ISSUE TITLE
Refactor the request service

### ISSUE THREAD

**Issue by kukukk** [OptimistikSAS/OIBus#981]
Instead of the single `sendRequest()` public method we should have separate methods to post a file, a json content or compressed json content and handle the content based on the called method instead of the custom header fields passed to `sendRequest()`

Maybe we should also separate the node-fetch and axios implementations into separate classes and use a factory to instantiate the right one based on the stack configured in Enginge.

**Comment by burgerni10** [comment]
In the refactoring process, it would be nice to add some comments on the sendRequest functions about the ApiHandler.STATUS
