### ISSUE TITLE
[Web Client] - OIbAuthentication from new config fails to correctly refresh the form when changing inputs

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#995]
**Describe the bug**
When adding a connector with the OIbAuthentication, if you change the username directly, the password disappears.

**To Reproduce**
1. Go to a new connector with OIbAuthentication (like OIAnalytics)
2. Update the username field
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/28055217/102632851-e67b6380-414f-11eb-9028-7a1c5dc1ed30.png)

**Comment by jfhenon** [comment]
can't reproduce. Did you run build-client ?

**Comment by burgerni10** [comment]
Indeed it was a problem with my web client not refreshed. The problem is on the NorthCsvToHttp branch. @victor-tndl, since it occurs on your branch, can you make sure it is fixed ?

**Comment by victor-tndl** [comment]
Seems to be good for me
